apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: 21813-project
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: frontend
    spec:
      serviceAccountName: nginx-sa
      containers:
      - name: mycontainer
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        - secretRef:
            name: nginx-secret
        volumeMounts:
        - name: nginx-volume
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: nginx-volume
        persistentVolumeClaim:
          claimName: nginx-pvc
