apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-rolebinding
subjects:
  - kind: ServiceAccount
    name: default   # Change this if you're using a custom service account
    namespace: default
roleRef:
  kind: Role
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io
